### ISSUE TITLE
Clarification needed on `POST api/register` Implementation

### ISSUE THREAD

**Issue by osman-butt** [who-knows-inc/KEA_DAT_DevOps_2024_Autumn#46]
## Description
According to the OpenAPI spec for the `POST api/register` endpoint, the request body should look like:

![OpenAPI Spec](https://github.com/user-attachments/assets/4f4411f6-5817-4050-8871-510af239686c)

However, the legacy code implementation for the `POST api/register` route is as follows:

![Legacy Code](https://github.com/user-attachments/assets/11f9811e-3acc-42d2-bb9b-5fa121dc7ad6)

### Questions:

**1. Which implementation is correct according to the current requirements?**

**2. Which implementation is the simulation using?**

**Comment by anderslatif** [comment]
Email is missing in the spec and password2 is optional. It will be sent but it's up to your API to use it or not. 
I have updated the OpenAPI Spec. Thank you for pointing this out.
