### ISSUE TITLE
Discrepancy between OpenAPI Spec and Simulation for `/api/search` Endpoint

### ISSUE THREAD

**Issue by osman-butt** [who-knows-inc/KEA_DAT_DevOps_2024_Autumn#47]
## Description
There is a discrepancy between the OpenAPI specification and the implementation in the simulation of the `/api/search` endpoint:

- **OpenAPI Spec**: Defines a `GET` request for `/api/search`.

![image](https://github.com/user-attachments/assets/068a3ba5-96c1-4b74-80fd-48879bd6699e)

- **Simulation Implementation**: Uses a `POST` request for `/api/search`.

![image](https://github.com/user-attachments/assets/366bdb87-ec32-4873-a1a3-a7b994c30330)

### Questions:

**1. Shouldn't the simulation adhere to the OpenAPI spec?**

**Comment by anderslatif** [comment]
It is a GET. I have fixed the simulator so that it will make searches to the API as GET. Thanks for pointing this out.
